// <auto-generated />
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace music_app_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251005095307_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.OwnsOne("Api.Models.Grid", "ChordGrid", b1 =>
                        {
                            b1.Property<int>("SongId")
                                .HasColumnType("integer");

                            b1.Property<string>("Synth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SongId");

                            b1.ToTable("Song");

                            b1.ToJson("ChordGrid");

                            b1.WithOwner()
                                .HasForeignKey("SongId");

                            b1.OwnsMany("Api.Models.GridColumn", "Columns", b2 =>
                                {
                                    b2.Property<int>("GridSongId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Duration")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.PrimitiveCollection<string[]>("Notes")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.HasKey("GridSongId", "__synthesizedOrdinal");

                                    b2.ToTable("Song");

                                    b2.WithOwner()
                                        .HasForeignKey("GridSongId");
                                });

                            b1.Navigation("Columns");
                        });

                    b.OwnsOne("Api.Models.Grid", "MelodyGrid", b1 =>
                        {
                            b1.Property<int>("SongId")
                                .HasColumnType("integer");

                            b1.Property<string>("Synth")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("SongId");

                            b1.ToTable("Song");

                            b1.ToJson("MelodyGrid");

                            b1.WithOwner()
                                .HasForeignKey("SongId");

                            b1.OwnsMany("Api.Models.GridColumn", "Columns", b2 =>
                                {
                                    b2.Property<int>("GridSongId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    b2.Property<string>("Duration")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.PrimitiveCollection<string[]>("Notes")
                                        .IsRequired()
                                        .HasColumnType("text[]");

                                    b2.HasKey("GridSongId", "__synthesizedOrdinal");

                                    b2.ToTable("Song");

                                    b2.WithOwner()
                                        .HasForeignKey("GridSongId");
                                });

                            b1.Navigation("Columns");
                        });

                    b.Navigation("ChordGrid")
                        .IsRequired();

                    b.Navigation("MelodyGrid")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
