// <auto-generated />
using Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace music_app_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("Api.Models.Song", b =>
                {
                    b.OwnsMany("Api.Models.GridColumn", "ChordGrid", b1 =>
                        {
                            b1.Property<int>("SongId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Duration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string[]>("Notes")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("SongId", "__synthesizedOrdinal");

                            b1.ToTable("Song");

                            b1.ToJson("ChordGrid");

                            b1.WithOwner()
                                .HasForeignKey("SongId");
                        });

                    b.OwnsMany("Api.Models.GridColumn", "MelodyGrid", b1 =>
                        {
                            b1.Property<int>("SongId")
                                .HasColumnType("integer");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<string>("Duration")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.PrimitiveCollection<string[]>("Notes")
                                .IsRequired()
                                .HasColumnType("text[]");

                            b1.HasKey("SongId", "__synthesizedOrdinal");

                            b1.ToTable("Song");

                            b1.ToJson("MelodyGrid");

                            b1.WithOwner()
                                .HasForeignKey("SongId");
                        });

                    b.Navigation("ChordGrid");

                    b.Navigation("MelodyGrid");
                });
#pragma warning restore 612, 618
        }
    }
}
